# Generated by Django 4.1.7 on 2023-04-05 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_signup'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_link',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
