# Generated by Django 4.1.7 on 2023-04-05 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_course_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='video_link',
            field=models.URLField(null=True),
        ),
    ]
