# Generated by Django 4.1.7 on 2023-04-05 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_course_video_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='video_link',
        ),
    ]
